name: JS Actions

on:
  pull_request_target:
    types: [closed]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: prs-reply
        uses: ./.github/actions/pr-reply
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
